# Generated by Django 4.2.1 on 2023-10-04 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_moddalar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
                ('pdf', models.FileField(upload_to='books/')),
                ('jpg', models.ImageField(upload_to='booksImg/')),
            ],
        ),
    ]
